sudo: required
services:
  - docker


before_install:
  - docker build -t lchimeddorj22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lchimeddorj22/react-test npm test -- --coverage


after_success:
  - docker build -t lchimeddorj22/multi-client ./client
  - docker build -t lchimeddorj22/multi-nginx ./nginx
  - docker build -t lchimeddorj22/multi-server ./server
  - docker build -t lchimeddorj22/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin